### ISSUE TITLE
Fix - Update documentation to reflect --beacon-addr to --bootstrap-addr

### ISSUE THREAD

**Issue by acravenho** [marlinprotocol/marlinctl2#1]
While updating my beacon from `marlinctl` to `marlinctl2` the documentation located [here](https://hackmd.io/@7IsSNyS5T5KC3HPNYavJwA/HJkv6RtTP) states: 

```
sudo marlinctl beacon create --discovery-addr "0.0.0.0:8002" --heartbeat-addr "0.0.0.0:8003" --beacon-addr "34.82.79.68:8003" --keystore-path /path/to/keystore --keystore-pass-path /path/to/passphrase
```

The `--beacon-addr` flag should be `--bootstrap-addr` pursuant the commit [here](https://github.com/marlinprotocol/marlinctl2/commit/04c6147bf4cd9c0ec1e756631b88db83824d6e79).

-LiveByCode

**Comment by supragya** [comment]
Fixed on HackMD! Thanks for heads up
