### ISSUE TITLE
How to slove "System does not have supervisor in running state"?

### ISSUE THREAD

**Issue by calify** [marlinprotocol/marlinctl2#2]
When I run this command, It doesn't work:
`sudo marlinctl beacon create --discovery-addr "0.0.0.0:8002" --heartbeat-addr "0.0.0.0:8003" --bootstrap-addr "34.82.79.68:8003" --keystore-path /home/ubuntu/marlin/key/keystore --keystore-pass-path /home/ubuntu/marlin/key/passphrase`

The result is:
`ERROR Failure during pre run sanity: System does not have supervisor in running state`

**Comment by roshanr95** [comment]
Usually happens when supervisor isn't installed or isn't running.

Run `which supervisord` to see if its installed (should print the path to supervisord) and run `sudo service supervisor status` to verify its running (should show `Active: active (running)`).

**Comment by calify** [comment]
> Hi @calify . Can you verify if the issue was what @roshanr95 diagnosed? we will then be able to close the issue.

It works, thanks
